### ISSUE TITLE
Definizione Tabelle Database

### ISSUE THREAD

**Issue by LindyBarby** [samuele-visentin/unipd-TecWeb#1]
Definizione delle tabelle con relativi campi e dimensioni
Nota: per facilitare la normalizzazione si può gestire ogni tupla con un identificativo

Tabella utente:
* ID Utente
* Username
* Email
* Password (crittografata)
* IsAdministrator (vedere se gestire semplicemente un utente da un amministratore da un flag oppure se pensare ad una tabella per la gestione dei ruoli - più complessa, più facile da gestire come flag dato che non è argomento di valutazione)

Tabella indagini
* ID Indagine
* Nome indagine
* Descrizione indagine
* Data inserimento (giusto per farla vedere in caso)

nota: meglio non mettere l'identificativo da qui in poi perché un indagine può avere solo un capitolo 1, un capitolo può avere solo una domanda n.1 etc. Visto che successivamente le tabelle comunque dovranno prendere le chiavi primarie complesse, forse è più facile aggiungere un identificativo capitolo, identificativo risposta, eccetera. Valuta la soluzione migliore.

Tabella capitoli:
* ID Indagine
* Progressivo capitolo
* Descrizione capitolo (giusto per farla vedere in caso)

Tabella risposte possibili:
* ID Indagine
* Progressivo capitolo
* Progressivo domanda
* Codice risposta (A, B, C)
* Descrizione risposta

Tabella domande:
* ID Indagine
* Progressivo capitolo
* Progressivo domanda
* Descrizione Domanda
* Codice Risposta Corretta

nota: meglio inserire il codice della risposta corretta nella domanda, oppure aggiungere una nuova tabella "Risposta" dove si fa il collegamento tra la tabella delle risposte e quella delle domande?

Tabella Salvataggi
nota: la chiave sarà id utente-id indagine. Un utente non può avere più salvataggi sulla stessa indagine.
nota2: Quando l'utente risolverà un capitolo automaticamente il salvataggio andrà sul capitolo successivo ma su ultima domanda risposta 0.
* ID Utente
* ID Indagine
* ID Capitolo
* Ultima domanda risposta

Tabella prove
* ID Prova
* ID Indagine
* Tipo prova (evento / testimonianza / indizio)
* CapitoloDisponibile (definisce da quale capitolo sarà disponibile l'indizio, sapendo 1 -> disponibile da subito (capitolo 1 è il primo da risolvere difatti). Banalmente si può fare una select dove si joina la tabella salvataggi su idCapitolo = capitoloDisponibile.

**Comment by samuele-visentin** [comment]
Schema ER e file di creazione del database inviati su telegram
