### ISSUE TITLE
Pagina Login / Sign Up

### ISSUE THREAD

**Issue by LindyBarby** [samuele-visentin/unipd-TecWeb#17]
Creazione pagina Login/Sign Up:
Visualizzazione della sezione Login e Sign Up (due pagine separate ma con codice simile) per poter fare il login sia da utente "normale" che da utente amministratore.

- HTML
- CSS aggiuntivo
- PHP
- Javascript (eventuale)

**Comment by isha141** [comment]
Hey, I want to do fix this issue
