### ISSUE TITLE
Pagina Lista Utenti

### ISSUE THREAD

**Issue by LindyBarby** [samuele-visentin/unipd-TecWeb#18]
Creazione pagina Lista Utenti (Amministratore)
Visualizzazione della di Lista Utenti per poter vedere gli utenti registrati così da poterne modificare i dati o cancellarli. (potrebbe anche essere una semplice tabella)

- HTML
- CSS aggiuntivo
- PHP
- Javascript (eventuale)

**Comment by samuele-visentin** [comment]
Pagina fatta ma da committare sulla repo
